add gh issue templates
luizirber/niffler pull request #47
Opened 2021-10-21 09:22 UTC by Ebedthan

I have added Github Issue templates to ease the submission of suggestions or bug reports.

2021-10-21 10:43 UTC, natir commented on .github/ISSUE_TEMPLATE/bug_report.md
> +2. Click on '....'
Not realy relevant in our case

2021-10-21 10:46 UTC, natir requested changes

2021-10-21 10:46 UTC, natir commented on .github/ISSUE_TEMPLATE/bug_report.md
> +4. See error
This example isn't really relevant in our case.

2021-10-21 10:46 UTC, natir commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots to help explain your problem.
Same as above

2021-10-21 10:46 UTC, natir commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Version [e.g. 22]
Same as above, but maybe we can keep it

2021-10-21 18:54 UTC, Ebedthan commented on .github/ISSUE_TEMPLATE/bug_report.md
> +4. See error
I've made some changes as you suggested. Hope it's more relevant now.

2021-10-21 19:31 UTC, natir commented
Thanks for your work it's seems realy nice.

2021-10-21 20:47 UTC, natir commented
I want solve MSRV (PR #48) before merge this but it's ok for me.

2021-12-12 00:16 UTC, luizirber approved these changes

2021-12-12 00:17 UTC, merged